# Generated by Django 3.2.13 on 2022-11-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221102_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hitCount',
            field=models.IntegerField(default=0),
        ),
    ]
