# Generated by Django 3.2.13 on 2022-11-04 02:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_celsius'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='celsius_check',
            field=models.ManyToManyField(related_name='check_celsius', to=settings.AUTH_USER_MODEL),
        ),
    ]
