# Generated by Django 3.2.13 on 2022-11-04 05:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20221104_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='celsius_minus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='celsius_plus',
        ),
        migrations.AddField(
            model_name='user',
            name='block_user',
            field=models.ManyToManyField(related_name='block', to=settings.AUTH_USER_MODEL),
        ),
    ]
