# Generated by Django 3.2.13 on 2022-11-04 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221104_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='block_user',
        ),
        migrations.AddField(
            model_name='user',
            name='blocking',
            field=models.ManyToManyField(related_name='blockers', to=settings.AUTH_USER_MODEL),
        ),
    ]
