# Generated by Django 3.2.13 on 2022-11-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='long_text',
        ),
        migrations.RemoveField(
            model_name='directmessage',
            name='short_text',
        ),
    ]
