# Generated by Django 3.2.13 on 2022-11-02 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_alter_directmessage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directmessage',
            name='who',
        ),
        migrations.AddField(
            model_name='directmessage',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_name', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageroom',
            name='last_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last', to=settings.AUTH_USER_MODEL),
        ),
    ]
