# Generated by Django 3.2.13 on 2022-11-01 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_original_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='user',
        ),
    ]
