# Generated by Django 3.2.13 on 2022-11-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='input_lat',
        ),
        migrations.RemoveField(
            model_name='location',
            name='input_lon',
        ),
        migrations.AddField(
            model_name='location',
            name='trade_locationx',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='trade_locationy',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
