# Generated by Django 3.2.13 on 2022-11-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221103_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='hit',
            field=models.IntegerField(default=0),
        ),
    ]
