# Generated by Django 3.2.13 on 2022-11-04 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_products_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='zzim',
            field=models.ManyToManyField(related_name='zzim_pro', to=settings.AUTH_USER_MODEL),
        ),
    ]
