# Generated by Django 3.2.13 on 2022-11-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_zzim'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
